export const CONST_APIS = {
  SERVER_URL: "https://api.ecoflowvn.vn/api/member",
  FEATURES: {
    AUTH: {
      LOGIN: "login",
      LOGOUT: "logout",
      GET_ME: "get-me",
      RESET_PASSWORD: "reset-password",
      REGISTER: "register",
      CHANGE_PASSWORD: "change-password",
      UPDATE: "update",
    },
    COMMON: {
      AUTH: "auth",
      PRODUCT: "product",
      CATEGORY: "category",
      CART: "cart",
      ORDER: "order",
      LAYOUT: "layout",
      ADVERTISE: "advertise",
      DOCUMENT: "document",
      WARRANTY: "warranty",
      BLOG: "blog",
      CONTACT: "contact",
      PRODUCT_REVIEWS: "product-reviews",
      PROPERTIES: "properties",
    },
  },
};

export const CONST_APIS_COMMON = {
  CREATE: "create",
  NEW_PRODUCT: "new-product",
  UPDATE: "update",
  GETALL: "get-all",
  PRODUCT_CATEGORY: "category-products",
  OPTION_PRODUCT: "option-product",
  ADD_CART: "add-cart",
  UPDATE_CART: "update-cart",
  DELETE_CART: "delete-cart",
  GET_ALL: "get-all",
  PRODUCT_BY_CATEGORY: "product-by-category",
  SHOW_ORDER: "show-order",
  GET_ORDER: "get-order",
  CHECKOUT: "checkout",
  GET_HEADER: "get-header",
  GET_FOOTER: "get-footer",
  GET_PRODUCTS_FOOTER: "get-products-footer",
  ABOUT_BRAND: "about-brand",
  SEARCH: "search",
  DOWNLOAD: "download",
  FIND_WARRANTY: "find-warranty",
  META: "meta",
  SEND_CONTACT: "send-contact",
};
